from peewee import *

DATABASE_BANE = 'vast.db'
db = SqliteDatabase(DATABASE_BANE)


class BaseModel(Model):
    class Meta:
        database = DATABASE_BANE


class Setting(BaseModel):
    id = IntegerField(primary_key=True)
    address = CharField()
    enable_log = BooleanField()
    log_directory = CharField()
    vast_api = CharField()

    def get(self):
        return (Setting
                .select()
                )[0]

    def saveAddr(self, addr: str):
        return (Setting.update({Setting.address: addr}).where(Setting.id==1))


class Instance(BaseModel):
    machine_id = IntegerField(primary_key=True)
    actual_status = CharField()
    bundle_id = IntegerField()
    bw_nvlink = FloatField()
    compute_cap = IntegerField()
    cpu_cores = IntegerField()
    cpu_cores_effective = FloatField()
    cpu_name = CharField()
    cpu_ram = IntegerField()
    cpu_util = FloatField()
    cuda_max_good = FloatField()
    cur_state = CharField()
    direct_port_count = IntegerField()
    direct_port_end = IntegerField()
    direct_port_start = IntegerField()
    disk_bw = FloatField()
    disk_name = CharField()
    disk_space = FloatField()
    disk_util = FloatField()
    dlperf = FloatField()
    dlperf_per_dphtotal = FloatField()
    dph_base = FloatField()
    dph_total = FloatField()
    driver_version = CharField()
    duration = FloatField()
    end_date = CharField()
    external = BooleanField()
    flops_per_dphtotal = FloatField()
    geolocation = CharField()
    gpu_display_active = BooleanField()
    gpu_frac = FloatField()
    gpu_lanes = IntegerField()
    gpu_mem_bw = FloatField()
    gpu_name = CharField()
    gpu_ram = IntegerField()
    gpu_temp = FloatField()
    gpu_util = FloatField()
    has_avx = IntegerField()
    host_id = IntegerField()
    hosting_type = IntegerField()
    id = IntegerField()
    image_args = CharField()
    image_runtype = CharField()
    image_uuid = CharField()
    inet_down = FloatField()
    inet_down_billed = FloatField()
    inet_down_cost = FloatField()
    inet_up = FloatField()
    inet_up_billed = FloatField()
    inet_up_cost = FloatField()
    intended_status = CharField()
    is_bid = BooleanField()
    jupyter_token = CharField()
    label = CharField()
    local_ipaddrs = CharField()
    logo = CharField()
    machine_dir_ssh_port = IntegerField()
    mem_limit = FloatField()
    mem_usage = FloatField()
    min_bid = FloatField()
    mobo_name = CharField()
    next_state = CharField()
    num_gpus = IntegerField()
    pci_gen = FloatField()
    pcie_bw = FloatField()
    ports = CharField()
    public_ipaddr = CharField()
    reliability2 = FloatField()
    rentable = BooleanField()
    score = FloatField()
    ssh_host = CharField()
    ssh_idx = CharField()
    ssh_port = IntegerField()
    start_date = FloatField()
    status_msg = CharField()
    storage_cost = FloatField()
    storage_total_cost = FloatField()
    total_flops = FloatField()
    verification = CharField()
    vmem_usage = FloatField()
    webpage = CharField()
